namespace api_sol
{
    public class DBEntitiy
    {
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
        public string col6 { get; set; }
        public string col7 { get; set; }
        public string col8 { get; set; }
        public string col9 { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public string col12 { get; set; }
        public string col13 { get; set; }
        public string col14 { get; set; }
        public string col15 { get; set; }
        public string col16 { get; set; }
        public string col17 { get; set; }
        public string col18 { get; set; }
        public string col19 { get; set; }
        public string col20 { get; set; }
        public string col21 { get; set; }
        public string col22 { get; set; }
        public string col23 { get; set; }
        public string col24 { get; set; }
        public string col25 { get; set; }
        public string col26 { get; set; }
        public string col27 { get; set; }
        public string col28 { get; set; }
        public string col29 { get; set; }
        public string col30 { get; set; }
        public string col31 { get; set; }
        public string col32 { get; set; }
        public string col33 { get; set; }
        public string col34 { get; set; }
        public string col35 { get; set; }
        public string col36 { get; set; }
        public string col37 { get; set; }
        public string col38 { get; set; }
        public string col39 { get; set; }
        public string col40 { get; set; }
        public string col41 { get; set; }
        public string col42 { get; set; }
        public string col43 { get; set; }
        public string col44 { get; set; }
        public string col45 { get; set; }
        public string col46 { get; set; }
        public string col47 { get; set; }
        public string col48 { get; set; }
        public string col49 { get; set; }
        public string col50 { get; set; }
        public string col51 { get; set; }
        public string col52 { get; set; }
        public string col53 { get; set; }
        public string col54 { get; set; }
        public string col55 { get; set; }
        public string col56 { get; set; }
        public string col57 { get; set; }
        public string col58 { get; set; }
        public string col59 { get; set; }
        public string col60 { get; set; }
        public string col61 { get; set; }
        public string col62 { get; set; }
        public string col63 { get; set; }
        public string col64 { get; set; }
        public string col65 { get; set; }
        public string col66 { get; set; }
        public string col67 { get; set; }
        public string col68 { get; set; }
        public string col69 { get; set; }
        public string col70 { get; set; }
        public string col71 { get; set; }
        public string col72 { get; set; }
        public string col73 { get; set; }
        public string col74 { get; set; }
        public string col75 { get; set; }
        public string col76 { get; set; }
        public string col77 { get; set; }
        public string col78 { get; set; }
        public string col79 { get; set; }
        public string col80 { get; set; }
        public string col81 { get; set; }
        public string col82 { get; set; }
        public string col83 { get; set; }
        public string col84 { get; set; }
        public string col85 { get; set; }
        public string col86 { get; set; }
        public string col87 { get; set; }
        public string col88 { get; set; }
        public string col89 { get; set; }
        public string col90 { get; set; }
        public string col91 { get; set; }
        public string col92 { get; set; }
        public string col93 { get; set; }
        public string col94 { get; set; }
        public string col95 { get; set; }
        public string col96 { get; set; }
        public string col97 { get; set; }
        public string col98 { get; set; }
        public string col99 { get; set; }
        public string col100 { get; set; }
        public string col101 { get; set; }
        public string col102 { get; set; }
        public string col103 { get; set; }
        public string col104 { get; set; }
        public string col105 { get; set; }
        public string col106 { get; set; }
        public string col107 { get; set; }
        public string col108 { get; set; }
        public string col109 { get; set; }
        public string col110 { get; set; }
        public string col111 { get; set; }
        public string col112 { get; set; }
        public string col113 { get; set; }
        public string col114 { get; set; }
        public string col115 { get; set; }
        public string col116 { get; set; }
        public string col117 { get; set; }
        public string col118 { get; set; }
        public string col119 { get; set; }
        public string col120 { get; set; }
        public string col121 { get; set; }
        public string col122 { get; set; }
        public string col123 { get; set; }
        public string col124 { get; set; }
        public string col125 { get; set; }
        public string col126 { get; set; }
        public string col127 { get; set; }
        public string col128 { get; set; }
        public string col129 { get; set; }
        public string col130 { get; set; }
        public string col131 { get; set; }
        public string col132 { get; set; }
        public string col133 { get; set; }
        public string col134 { get; set; }
        public string col135 { get; set; }
        public string col136 { get; set; }
        public string col137 { get; set; }
        public string col138 { get; set; }
        public string col139 { get; set; }
        public string col140 { get; set; }
        public string col141 { get; set; }
        public string col142 { get; set; }
        public string col143 { get; set; }
        public string col144 { get; set; }
        public string col145 { get; set; }
        public string col146 { get; set; }
        public string col147 { get; set; }
        public string col148 { get; set; }
        public string col149 { get; set; }
        public string col150 { get; set; }
        public string col151 { get; set; }
        public string col152 { get; set; }
        public string col153 { get; set; }
        public string col154 { get; set; }
        public string col155 { get; set; }
        public string col156 { get; set; }
        public string col157 { get; set; }
        public string col158 { get; set; }
        public string col159 { get; set; }
        public string col160 { get; set; }
        public string col161 { get; set; }
        public string col162 { get; set; }
        public string col163 { get; set; }
        public string col164 { get; set; }
        public string col165 { get; set; }
        public string col166 { get; set; }
        public string col167 { get; set; }
        public string col168 { get; set; }
        public string col169 { get; set; }
        public string col170 { get; set; }
        public string col171 { get; set; }
        public string col172 { get; set; }
        public string col173 { get; set; }
        public string col174 { get; set; }
        public string col175 { get; set; }
        public string col176 { get; set; }
        public string col177 { get; set; }
        public string col178 { get; set; }
        public string col179 { get; set; }
        public string col180 { get; set; }
        public string col181 { get; set; }
        public string col182 { get; set; }
        public string col183 { get; set; }
        public string col184 { get; set; }
        public string col185 { get; set; }
        public string col186 { get; set; }
        public string col187 { get; set; }
        public string col188 { get; set; }
        public string col189 { get; set; }
        public string col190 { get; set; }
        public string col191 { get; set; }
        public string col192 { get; set; }
        public string col193 { get; set; }
        public string col194 { get; set; }
        public string col195 { get; set; }
        public string col196 { get; set; }
        public string col197 { get; set; }
        public string col198 { get; set; }
        public string col199 { get; set; }
        public string col200 { get; set; }
        public string col201 { get; set; }
        public string col202 { get; set; }
        public string col203 { get; set; }
        public string col204 { get; set; }
        public string col205 { get; set; }
        public string col206 { get; set; }
        public string col207 { get; set; }
        public string col208 { get; set; }
        public string col209 { get; set; }
        public string col210 { get; set; }
        public string col211 { get; set; }
        public string col212 { get; set; }
        public string col213 { get; set; }
        public string col214 { get; set; }
        public string col215 { get; set; }
        public string col216 { get; set; }
        public string col217 { get; set; }
        public string col218 { get; set; }
        public string col219 { get; set; }
        public string col220 { get; set; }
        public string col221 { get; set; }
        public string col222 { get; set; }
        public string col223 { get; set; }
        public string col224 { get; set; }
        public string col225 { get; set; }
        public string col226 { get; set; }
        public string col227 { get; set; }
        public string col228 { get; set; }
        public string col229 { get; set; }
        public string col230 { get; set; }
        public string col231 { get; set; }
        public string col232 { get; set; }
        public string col233 { get; set; }
        public string col234 { get; set; }
        public string col235 { get; set; }
        public string col236 { get; set; }
        public string col237 { get; set; }
        public string col238 { get; set; }
        public string col239 { get; set; }
        public string col240 { get; set; }
        public string col241 { get; set; }
        public string col242 { get; set; }
        public string col243 { get; set; }
        public string col244 { get; set; }
        public string col245 { get; set; }
        public string col246 { get; set; }
        public string col247 { get; set; }
        public string col248 { get; set; }
        public string col249 { get; set; }
        public string col250 { get; set; }
        public string col251 { get; set; }
        public string col252 { get; set; }
        public string col253 { get; set; }
        public string col254 { get; set; }
        public string col255 { get; set; }
        public string col256 { get; set; }
        public string col257 { get; set; }
        public string col258 { get; set; }
        public string col259 { get; set; }
        public string col260 { get; set; }
        public string col261 { get; set; }
        public string col262 { get; set; }
        public string col263 { get; set; }
        public string col264 { get; set; }
        public string col265 { get; set; }
        public string col266 { get; set; }
        public string col267 { get; set; }
        public string col268 { get; set; }
        public string col269 { get; set; }
        public string col270 { get; set; }
        public string col271 { get; set; }
        public string col272 { get; set; }
        public string col273 { get; set; }
        public string col274 { get; set; }
        public string col275 { get; set; }
        public string col276 { get; set; }
        public string col277 { get; set; }
        public string col278 { get; set; }
        public string col279 { get; set; }
        public string col280 { get; set; }
        public string col281 { get; set; }
        public string col282 { get; set; }
        public string col283 { get; set; }
        public string col284 { get; set; }
        public string col285 { get; set; }
        public string col286 { get; set; }
        public string col287 { get; set; }
        public string col288 { get; set; }
        public string col289 { get; set; }
        public string col290 { get; set; }
        public string col291 { get; set; }
        public string col292 { get; set; }
        public string col293 { get; set; }
        public string col294 { get; set; }
        public string col295 { get; set; }
        public string col296 { get; set; }
        public string col297 { get; set; }
        public string col298 { get; set; }
        public string col299 { get; set; }
        public string col300 { get; set; }
        public string col301 { get; set; }
        public string col302 { get; set; }
        public string col303 { get; set; }
        public string col304 { get; set; }
        public string col305 { get; set; }
        public string col306 { get; set; }
        public string col307 { get; set; }
        public string col308 { get; set; }
        public string col309 { get; set; }
        public string col310 { get; set; }
        public string col311 { get; set; }
        public string col312 { get; set; }
        public string col313 { get; set; }
        public string col314 { get; set; }
        public string col315 { get; set; }
        public string col316 { get; set; }
        public string col317 { get; set; }
        public string col318 { get; set; }
        public string col319 { get; set; }
        public string col320 { get; set; }
        public string col321 { get; set; }
        public string col322 { get; set; }
        public string col323 { get; set; }
        public string col324 { get; set; }
        public string col325 { get; set; }
        public string col326 { get; set; }
        public string col327 { get; set; }
        public string col328 { get; set; }
        public string col329 { get; set; }
        public string col330 { get; set; }
        public string col331 { get; set; }
        public string col332 { get; set; }
        public string col333 { get; set; }
        public string col334 { get; set; }
        public string col335 { get; set; }
        public string col336 { get; set; }
        public string col337 { get; set; }
        public string col338 { get; set; }
        public string col339 { get; set; }
        public string col340 { get; set; }
        public string col341 { get; set; }
        public string col342 { get; set; }
        public string col343 { get; set; }
        public string col344 { get; set; }
        public string col345 { get; set; }
        public string col346 { get; set; }
        public string col347 { get; set; }
        public string col348 { get; set; }
        public string col349 { get; set; }
        public string col350 { get; set; }
        public string col351 { get; set; }
        public string col352 { get; set; }
        public string col353 { get; set; }
        public string col354 { get; set; }
        public string col355 { get; set; }
        public string col356 { get; set; }
        public string col357 { get; set; }
        public string col358 { get; set; }
        public string col359 { get; set; }
        public string col360 { get; set; }
        public string col361 { get; set; }
        public string col362 { get; set; }
        public string col363 { get; set; }
        public string col364 { get; set; }
        public string col365 { get; set; }
        public string col366 { get; set; }
        public string col367 { get; set; }
        public string col368 { get; set; }
        public string col369 { get; set; }
        public string col370 { get; set; }
        public string col371 { get; set; }
        public string col372 { get; set; }
        public string col373 { get; set; }
        public string col374 { get; set; }
        public string col375 { get; set; }
        public string col376 { get; set; }
        public string col377 { get; set; }
        public string col378 { get; set; }
        public string col379 { get; set; }
        public string col380 { get; set; }
        public string col381 { get; set; }
        public string col382 { get; set; }
        public string col383 { get; set; }
        public string col384 { get; set; }
        public string col385 { get; set; }
        public string col386 { get; set; }
        public string col387 { get; set; }
        public string col388 { get; set; }
        public string col389 { get; set; }
        public string col390 { get; set; }
        public string col391 { get; set; }
        public string col392 { get; set; }
        public string col393 { get; set; }
        public string col394 { get; set; }
        public string col395 { get; set; }
        public string col396 { get; set; }
        public string col397 { get; set; }
        public string col398 { get; set; }
        public string col399 { get; set; }
        public string col400 { get; set; }
        public string col401 { get; set; }
        public string col402 { get; set; }
        public string col403 { get; set; }
        public string col404 { get; set; }
        public string col405 { get; set; }
        public string col406 { get; set; }
        public string col407 { get; set; }
        public string col408 { get; set; }
        public string col409 { get; set; }
        public string col410 { get; set; }
        public string col411 { get; set; }
        public string col412 { get; set; }
        public string col413 { get; set; }
        public string col414 { get; set; }
        public string col415 { get; set; }
        public string col416 { get; set; }
        public string col417 { get; set; }
        public string col418 { get; set; }
        public string col419 { get; set; }
        public string col420 { get; set; }
        public string col421 { get; set; }
        public string col422 { get; set; }
        public string col423 { get; set; }
        public string col424 { get; set; }
        public string col425 { get; set; }
        public string col426 { get; set; }
        public string col427 { get; set; }
        public string col428 { get; set; }
        public string col429 { get; set; }
        public string col430 { get; set; }
        public string col431 { get; set; }
        public string col432 { get; set; }
        public string col433 { get; set; }
        public string col434 { get; set; }
        public string col435 { get; set; }
        public string col436 { get; set; }
        public string col437 { get; set; }
        public string col438 { get; set; }
        public string col439 { get; set; }
        public string col440 { get; set; }
        public string col441 { get; set; }
        public string col442 { get; set; }
        public string col443 { get; set; }
        public string col444 { get; set; }
        public string col445 { get; set; }
        public string col446 { get; set; }
        public string col447 { get; set; }
        public string col448 { get; set; }
        public string col449 { get; set; }
        public string col450 { get; set; }
    }

}
